apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "scjob_patroni_fullname" . }}
    cluster-name: {{ template "scjob_patroni_fullname" . }}
    component: {{ .Values.patroni.componentName }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
  name: {{ template "scjob_patroni_fullname" . }}