kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.componentName }}
spec:
  podSelector:
    matchLabels:
      name: postgresql
  ingress:
    - ports:
        - protocol: TCP
          port: 5432
      from:
        - podSelector:
            matchLabels:
              app: scj-booking
  policyTypes:
    - Ingress
