kind: Template
apiVersion: v1
metadata:
  name: scj-booking-build
  annotations:
    openshift.io/display-name: SCJ Online Booking BuildConfig
    description: Online Booking System for British Columbia Superior Courts
    tags: dotnet
    iconClass: icon-dotnet
    template.openshift.io/provider-display-name: Red Hat, Inc.
    template.openshift.io/documentation-url: https://github.com/redhat-developer/s2i-dotnetcore
    template.openshift.io/support-url: https://access.redhat.com
labels:
  template: scj-booking-build
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}-runtime
      annotations:
        description: Keeps track of changes in the application runtime image
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}-build
      annotations:
        description: Keeps track of changes in the application builder image
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: patroni-postgres
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: pgbouncer
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: backup-container
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}-build
      annotations:
        description: Defines how to build the application
    spec:
      source:
        type: Git
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
        contextDir: ${CONTEXT_DIR}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: DockerImage
            name: ${DOTNET_BUILD_DOCKER_IMAGE}
          env:
            - name: DOTNET_STARTUP_PROJECT
              value: ${DOTNET_STARTUP_PROJECT}
            - name: DOTNET_SDK_VERSION
              value: ${DOTNET_SDK_VERSION}
            - name: DOTNET_ASSEMBLY_NAME
              value: ${DOTNET_ASSEMBLY_NAME}
            - name: DOTNET_NPM_TOOLS
              value: ${DOTNET_NPM_TOOLS}
            - name: DOTNET_TEST_PROJECTS
              value: ${DOTNET_TEST_PROJECTS}
            - name: DOTNET_CONFIGURATION
              value: ${DOTNET_CONFIGURATION}
            - name: DOTNET_RESTORE_SOURCES
              value: ${DOTNET_RESTORE_SOURCES}
            - name: DOTNET_PACK
              value: "true"
            - name: DOTNET_TOOLS
              value: ${DOTNET_TOOLS}
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}-build:latest
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
        requests:
          cpu: "1"
          memory: 4Gi
      triggers:
        - type: GitHub
          github:
            secret: ${GITHUB_WEBHOOK_SECRET}
      postCommit: {}
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}-runtime
      annotations:
        description: Defines how to chain the runtime image from the source build image
    spec:
      source:
        dockerfile: |-
          FROM ${DOTNET_RUNTIME_DOCKER_IMAGE}
          ADD app.tar.gz .
        images:
          - from:
              kind: ImageStreamTag
              name: ${NAME}-build:latest
            paths:
              - sourcePath: /opt/app-root/app.tar.gz
                destinationDir: .
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: DockerImage
            name: ${DOTNET_RUNTIME_DOCKER_IMAGE}
      triggers:
          - type: ImageChange
            imageChange:
              from:
                kind: ImageStreamTag
                name: ${NAME}-build:latest
      resources:
        limits:
          cpu: '2'
          memory: 4Gi
        requests:
          cpu: '1'
          memory: 2Gi
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}-runtime:latest
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the frontend objects defined in this template.
    required: true
    value: scj-booking
  - name: DOTNET_RUNTIME_DOCKER_IMAGE
    displayName: .NET Runtime Imagestream Tag
    description: The docker image which is used to run the application.
    required: true
    value: registry.access.redhat.com/rhel8/dotnet-60-runtime:latest
  - name: DOTNET_BUILD_DOCKER_IMAGE
    displayName: .NET builder
    required: true
    description: The docker image which is used to build the application.
    value: registry.access.redhat.com/rhel8/dotnet-60:latest
  - name: NAMESPACE
    displayName: Namespace
    required: true
    description: The OpenShift Namespace where the .NET builder ImageStream resides.
    value: openshift
  - name: SOURCE_REPOSITORY_URL
    displayName: Git Repository URL
    required: true
    description: The URL of the repository with your application source code.
    value: https://github.com/bcgov/SCJ-Online-Booking.git
  - name: SOURCE_REPOSITORY_REF
    displayName: Git Reference
    description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch.
    value: master
  - name: CONTEXT_DIR
    displayName: Context Directory
    description: Set this to the relative path to your project if it is not in the root of your repository.
  - name: DOTNET_STARTUP_PROJECT
    displayName: Startup Project
    description: Set this to a project file (e.g. csproj) or a folder containing a single project file.
    value: app
  - name: DOTNET_SDK_VERSION
    displayName: SDK Version
    description: Set this to configure the default SDK version. This can be set to a specific version, '' (lowest version) or 'latest' (highest version).
    value: ""
  - name: DOTNET_ASSEMBLY_NAME
    displayName: Startup Assembly
    description: Set this when the assembly name is overridden in the project file.
  - name: DOTNET_TOOLS
    displayName: .NET Tools
    description: Set this to a space separated list of .NET tools needed to publish.
  - name: DOTNET_NPM_TOOLS
    displayName: Npm Tools
    description: Set this to a space separated list of npm tools needed to publish.
  - name: DOTNET_TEST_PROJECTS
    displayName: Test projects
    description: Set this to a space separated list of test projects to run before publishing.
    value: test
  - name: DOTNET_CONFIGURATION
    displayName: Configuration
    description: Set this to configuration (Release/Debug).
    value: Release
  - name: DOTNET_RESTORE_SOURCES
    displayName: NuGet package sources
    description: Set this to override the NuGet.config sources.
  - name: GITHUB_WEBHOOK_SECRET
    displayName: GitHub Webhook Secret
    description: A secret string used to configure the GitHub webhook.
    generate: expression
    from: '[a-zA-Z0-9]{40}'
