---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: "scj-booking-pipeline-template"

objects:
- kind: Pipeline
  apiVersion: tekton.dev/v1beta1
  metadata:    
    name: deploy-to-test
  spec:
    tasks:
      - name: deploy-app
        params:
          - name: IMAGE
            value: scj-booking-runtime
          - name: IMAGE_TAG
            value: latest
          - name: ENV
            value: test
        taskRef:
          kind: Task
          name: scj-deploy-with-tag
      - name: deploy-taskrunner
        params:
          - name: IMAGE
            value: scj-booking-taskrunner-runtime
          - name: IMAGE_TAG
            value: latest
          - name: ENV
            value: test
        taskRef:
          kind: Task
          name: scj-deploy-with-tag

- kind: Pipeline
  apiVersion: tekton.dev/v1beta1
  metadata:
    name: deploy-to-prod
  spec:
    tasks:
      - name: deploy-app
        params:
          - name: IMAGE
            value: scj-booking-runtime
          - name: IMAGE_TAG
            value: test
          - name: ENV
            value: prod
        taskRef:
          kind: Task
          name: scj-deploy-with-tag
      - name: deploy-taskrunner
        params:
          - name: IMAGE
            value: scj-booking-taskrunner-runtime
          - name: IMAGE_TAG
            value: test
          - name: ENV
            value: prod
        taskRef:
          kind: Task
          name: scj-deploy-with-tag

- apiVersion: tekton.dev/v1beta1
  kind: Task
  metadata:
    name: scj-deploy-with-tag
  spec:
    params:
      - description: The name given to the built image.
        name: IMAGE
        type: string
      - default: latest
        description: The tag given to the built image.
        name: IMAGE_TAG
        type: string
      - description: The environment to deploy to.
        name: ENV
        type: string
    steps:
      - image: 'image-registry.openshift-image-registry.svc:5000/openshift/cli:latest'
        name: deploy
        resources: {}
        script: |
          set -xe

          echo "Tagging image to trigger deployment to $(params.ENV)"

          oc tag $(params.IMAGE):$(params.IMAGE_TAG) $(params.IMAGE):$(params.ENV)
