<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://tempuri.org/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="OnlineBooking" targetNamespace="http://tempuri.org/">
  <wsp:Policy wsu:Id="BasicHttpBinding_IOnlineBooking_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:TransportBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:TransportToken>
              <wsp:Policy>
                <sp:HttpsToken RequireClientCertificate="false"/>
              </wsp:Policy>
            </sp:TransportToken>
            <sp:AlgorithmSuite>
              <wsp:Policy>
                <sp:Basic256/>
              </wsp:Policy>
            </sp:AlgorithmSuite>
            <sp:Layout>
              <wsp:Policy>
                <sp:Strict/>
              </wsp:Policy>
            </sp:Layout>
          </wsp:Policy>
        </sp:TransportBinding>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsdl:types>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
      <xs:import namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects"/>
      <xs:import namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking"/>
      <xs:import namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays"/>
      <xs:element name="scCaseNumberValid">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="caseNum" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="scCaseNumberValidResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q1="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects" minOccurs="0" name="scCaseNumberValidResult" nillable="true" type="q1:ArrayOfCourtFile"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="scGetLocations">
        <xs:complexType>
          <xs:sequence/>
        </xs:complexType>
      </xs:element>
      <xs:element name="scGetLocationsResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q2="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects" minOccurs="0" name="scGetLocationsResult" nillable="true" type="q2:ArrayOfLocation"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="scConfAvailableDatesByLocation">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="locationID" type="xs:int"/>
            <xs:element minOccurs="0" name="hearingTypeID" type="xs:int"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="scConfAvailableDatesByLocationResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q3="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects" minOccurs="0" name="scConfAvailableDatesByLocationResult" nillable="true" type="q3:AvailableDatesByLocation"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="scConfBookHearing">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q4="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking" minOccurs="0" name="bookInfo" nillable="true" type="q4:BookHearingInfo"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="scConfBookHearingResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q5="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking" minOccurs="0" name="scConfBookHearingResult" nillable="true" type="q5:BookingHearingResult"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="coaCaseNumberValid">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="caseNum" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="coaCaseNumberValidResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q6="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects" minOccurs="0" name="coaCaseNumberValidResult" nillable="true" type="q6:COACaseList"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="coaAvailableAppealDates">
        <xs:complexType>
          <xs:sequence/>
        </xs:complexType>
      </xs:element>
      <xs:element name="coaAvailableAppealDatesResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q7="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects" minOccurs="0" name="coaAvailableAppealDatesResult" nillable="true" type="q7:CoAAvailableDates"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="coaQueueAppealHearing">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q8="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking" minOccurs="0" name="bookingInfo" nillable="true" type="q8:CoABookingHearingInfo"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="coaQueueAppealHearingResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q9="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking" minOccurs="0" name="coaQueueAppealHearingResult" nillable="true" type="q9:BookingHearingResult"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="coaAvailableCHDates">
        <xs:complexType>
          <xs:sequence/>
        </xs:complexType>
      </xs:element>
      <xs:element name="coaAvailableCHDatesResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q10="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects" minOccurs="0" name="coaAvailableCHDatesResult" nillable="true" type="q10:CoAChambersAvailableDates"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="coaQueueCHHearing">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q11="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking" minOccurs="0" name="bookingInfo" nillable="true" type="q11:CoAChambersBookingHearingInfo"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="coaQueueCHHearingResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q12="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking" minOccurs="0" name="coaQueueCHHearingResult" nillable="true" type="q12:BookingHearingResult"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="coaCHApplicationList">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="type" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="coaCHApplicationListResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q13="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects" minOccurs="0" name="coaCHApplicationListResult" nillable="true" type="q13:ArrayOfCoAChambersApplications"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="scAvailableFormulasByHearingTypeAndLocation">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="locationID" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="formula" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="hearingTypeId" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="scAvailableFormulasByHearingTypeAndLocationResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q14="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects" minOccurs="0" name="scAvailableFormulasByHearingTypeAndLocationResult" nillable="true" type="q14:ArrayOfFormulaLocation"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="scAvailableDatesByHearingTypeAndLocation">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q15="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking" minOccurs="0" name="requestInfo" nillable="true" type="q15:AvailableTrialDatesRequestInfo"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="scAvailableDatesByHearingTypeAndLocationResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q16="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking" minOccurs="0" name="scAvailableDatesByHearingTypeAndLocationResult" nillable="true" type="q16:AvailableTrialDatesResult"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="scTrialBookHearing">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q17="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking" minOccurs="0" name="bookingInfo" nillable="true" type="q17:BookTrialHearingInfo"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="scTrialBookHearingResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q18="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking" minOccurs="0" name="scTrialBookHearingResult" nillable="true" type="q18:BookingHearingResult"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="scGetAvailableBookingTypes">
        <xs:complexType>
          <xs:sequence/>
        </xs:complexType>
      </xs:element>
      <xs:element name="scGetAvailableBookingTypesResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q19="http://schemas.microsoft.com/2003/10/Serialization/Arrays" minOccurs="0" name="scGetAvailableBookingTypesResult" nillable="true" type="q19:ArrayOfstring"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="scCHHearingSubType">
        <xs:complexType>
          <xs:sequence/>
        </xs:complexType>
      </xs:element>
      <xs:element name="scCHHearingSubTypeResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q20="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects" minOccurs="0" name="scCHHearingSubTypeResult" nillable="true" type="q20:ArrayOfSCCHHearingSubTypeDetails"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="scCHBookHearing">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q21="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking" minOccurs="0" name="bookInfo" nillable="true" type="q21:BookingSCCHHearingInfo"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="scCHBookHearingResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q22="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking" minOccurs="0" name="scCHBookHearingResult" nillable="true" type="q22:BookingHearingResult"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/">
      <xs:element name="anyType" nillable="true" type="xs:anyType"/>
      <xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
      <xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
      <xs:element name="boolean" nillable="true" type="xs:boolean"/>
      <xs:element name="byte" nillable="true" type="xs:byte"/>
      <xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
      <xs:element name="decimal" nillable="true" type="xs:decimal"/>
      <xs:element name="double" nillable="true" type="xs:double"/>
      <xs:element name="float" nillable="true" type="xs:float"/>
      <xs:element name="int" nillable="true" type="xs:int"/>
      <xs:element name="long" nillable="true" type="xs:long"/>
      <xs:element name="QName" nillable="true" type="xs:QName"/>
      <xs:element name="short" nillable="true" type="xs:short"/>
      <xs:element name="string" nillable="true" type="xs:string"/>
      <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
      <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
      <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
      <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
      <xs:element name="char" nillable="true" type="tns:char"/>
      <xs:simpleType name="char">
        <xs:restriction base="xs:int"/>
      </xs:simpleType>
      <xs:element name="duration" nillable="true" type="tns:duration"/>
      <xs:simpleType name="duration">
        <xs:restriction base="xs:duration">
          <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
          <xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
          <xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:element name="guid" nillable="true" type="tns:guid"/>
      <xs:simpleType name="guid">
        <xs:restriction base="xs:string">
          <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:attribute name="FactoryType" type="xs:QName"/>
      <xs:attribute name="Id" type="xs:ID"/>
      <xs:attribute name="Ref" type="xs:IDREF"/>
    </xs:schema>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects">
      <xs:complexType name="ArrayOfCourtFile">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="CourtFile" nillable="true" type="tns:CourtFile"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfCourtFile" nillable="true" type="tns:ArrayOfCourtFile"/>
      <xs:complexType name="CourtFile">
        <xs:sequence>
          <xs:element minOccurs="0" name="CEISLocationId" nillable="true" type="xs:decimal"/>
          <xs:element minOccurs="0" name="courtClassCode" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="courtFileNumber" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="courtLevelCode" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="fairUseSort" type="xs:int"/>
          <xs:element minOccurs="0" name="futureTrialHearing" type="xs:boolean"/>
          <xs:element minOccurs="0" name="physicalFileId" nillable="true" type="xs:decimal"/>
          <xs:element minOccurs="0" name="styleOfCause" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="CourtFile" nillable="true" type="tns:CourtFile"/>
      <xs:complexType name="ArrayOfLocation">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="Location" nillable="true" type="tns:Location"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfLocation" nillable="true" type="tns:ArrayOfLocation"/>
      <xs:complexType name="Location">
        <xs:sequence>
          <xs:element minOccurs="0" name="bookingHearingTypeID" type="xs:int"/>
          <xs:element minOccurs="0" name="bookingLocationID" type="xs:int"/>
          <xs:element minOccurs="0" name="locationCode" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="locationID" type="xs:int"/>
          <xs:element minOccurs="0" name="locationName" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="Location" nillable="true" type="tns:Location"/>
      <xs:complexType name="AvailableDatesByLocation">
        <xs:sequence>
          <xs:element minOccurs="0" name="AvailableDates" nillable="true" type="tns:ArrayOfContainerInfo"/>
          <xs:element minOccurs="0" name="BookingDetails" nillable="true" type="tns:BookingDetail"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="AvailableDatesByLocation" nillable="true" type="tns:AvailableDatesByLocation"/>
      <xs:complexType name="ArrayOfContainerInfo">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="ContainerInfo" nillable="true" type="tns:ContainerInfo"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfContainerInfo" nillable="true" type="tns:ArrayOfContainerInfo"/>
      <xs:complexType name="ContainerInfo">
        <xs:sequence>
          <xs:element minOccurs="0" name="ContainerID" type="xs:int"/>
          <xs:element minOccurs="0" name="Date_Time" type="xs:dateTime"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ContainerInfo" nillable="true" type="tns:ContainerInfo"/>
      <xs:complexType name="BookingDetail">
        <xs:sequence>
          <xs:element minOccurs="0" name="bookingNotes" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="detailBookingLength" type="xs:int"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="BookingDetail" nillable="true" type="tns:BookingDetail"/>
      <xs:complexType name="COACaseList">
        <xs:sequence>
          <xs:element minOccurs="0" name="CaseList" nillable="true" type="tns:ArrayOfCoAClassInfo"/>
          <xs:element minOccurs="0" name="CaseType" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="COACaseList" nillable="true" type="tns:COACaseList"/>
      <xs:complexType name="ArrayOfCoAClassInfo">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="CoAClassInfo" nillable="true" type="tns:CoAClassInfo"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfCoAClassInfo" nillable="true" type="tns:ArrayOfCoAClassInfo"/>
      <xs:complexType name="CoAClassInfo">
        <xs:sequence>
          <xs:element minOccurs="0" name="CaseId" type="xs:int"/>
          <xs:element minOccurs="0" name="Case_Num" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="Main" type="xs:boolean"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="CoAClassInfo" nillable="true" type="tns:CoAClassInfo"/>
      <xs:complexType name="CoAAvailableDates">
        <xs:sequence>
          <xs:element minOccurs="0" name="AvailableDates" nillable="true" type="tns:ArrayOfShedulesInfo"/>
          <xs:element minOccurs="0" name="BookingNotes" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="CoAAvailableDates" nillable="true" type="tns:CoAAvailableDates"/>
      <xs:complexType name="ArrayOfShedulesInfo">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="ShedulesInfo" nillable="true" type="tns:ShedulesInfo"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfShedulesInfo" nillable="true" type="tns:ArrayOfShedulesInfo"/>
      <xs:complexType name="ShedulesInfo">
        <xs:sequence>
          <xs:element minOccurs="0" name="availability" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="scheduleDate" type="xs:dateTime"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ShedulesInfo" nillable="true" type="tns:ShedulesInfo"/>
      <xs:complexType name="CoAChambersAvailableDates">
        <xs:sequence>
          <xs:element minOccurs="0" name="AvailableDates" nillable="true" type="tns:ArrayOfCoAChambersShedulesInfo"/>
          <xs:element minOccurs="0" name="BookingNotes" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="CoAChambersAvailableDates" nillable="true" type="tns:CoAChambersAvailableDates"/>
      <xs:complexType name="ArrayOfCoAChambersShedulesInfo">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="CoAChambersShedulesInfo" nillable="true" type="tns:CoAChambersShedulesInfo"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfCoAChambersShedulesInfo" nillable="true" type="tns:ArrayOfCoAChambersShedulesInfo"/>
      <xs:complexType name="CoAChambersShedulesInfo">
        <xs:sequence>
          <xs:element minOccurs="0" name="availability" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="scheduleDate" type="xs:dateTime"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="CoAChambersShedulesInfo" nillable="true" type="tns:CoAChambersShedulesInfo"/>
      <xs:complexType name="ArrayOfCoAChambersApplications">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="CoAChambersApplications" nillable="true" type="tns:CoAChambersApplications"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfCoAChambersApplications" nillable="true" type="tns:ArrayOfCoAChambersApplications"/>
      <xs:complexType name="CoAChambersApplications">
        <xs:sequence>
          <xs:element minOccurs="0" name="ApplicationTypeDefinition" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="ApplicationTypeName" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="HearingTypeID" type="xs:int"/>
          <xs:element minOccurs="0" name="Timeline" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="CoAChambersApplications" nillable="true" type="tns:CoAChambersApplications"/>
      <xs:complexType name="ArrayOfFormulaLocation">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="FormulaLocation" nillable="true" type="tns:FormulaLocation"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfFormulaLocation" nillable="true" type="tns:ArrayOfFormulaLocation"/>
      <xs:complexType name="FormulaLocation">
        <xs:sequence>
          <xs:element minOccurs="0" name="BookingHearingCode" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="BookingLocationID" type="xs:int"/>
          <xs:element minOccurs="0" name="EndDate" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="FairUseBookingPeriodEndDate" nillable="true" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="FairUseBookingPeriodStartDate" nillable="true" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="FairUseContactDate" nillable="true" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="FormulaType" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="HearingTypeId" type="xs:int"/>
          <xs:element minOccurs="0" name="LocationCode" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="LocationID" type="xs:int"/>
          <xs:element minOccurs="0" name="LocationName" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="StartDate" type="xs:dateTime"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="FormulaLocation" nillable="true" type="tns:FormulaLocation"/>
      <xs:complexType name="AvailableTrialDates">
        <xs:sequence>
          <xs:element minOccurs="0" name="AvailablesDatesInfo" nillable="true" type="tns:ArrayOfAvailableTrialDatesInfo"/>
          <xs:element minOccurs="0" name="BookingHearingCode" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="BookingLocationID" type="xs:int"/>
          <xs:element minOccurs="0" name="FormulaType" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="LocationCode" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="LocationID" type="xs:int"/>
          <xs:element minOccurs="0" name="LocationName" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="AvailableTrialDates" nillable="true" type="tns:AvailableTrialDates"/>
      <xs:complexType name="ArrayOfAvailableTrialDatesInfo">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="AvailableTrialDatesInfo" nillable="true" type="tns:AvailableTrialDatesInfo"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfAvailableTrialDatesInfo" nillable="true" type="tns:ArrayOfAvailableTrialDatesInfo"/>
      <xs:complexType name="AvailableTrialDatesInfo">
        <xs:sequence>
          <xs:element minOccurs="0" name="AvailableDate" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="AvailableQuantity" type="xs:int"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="AvailableTrialDatesInfo" nillable="true" type="tns:AvailableTrialDatesInfo"/>
      <xs:complexType name="ArrayOfSCCHHearingSubTypeDetails">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="SCCHHearingSubTypeDetails" nillable="true" type="tns:SCCHHearingSubTypeDetails"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfSCCHHearingSubTypeDetails" nillable="true" type="tns:ArrayOfSCCHHearingSubTypeDetails"/>
      <xs:complexType name="SCCHHearingSubTypeDetails">
        <xs:sequence>
          <xs:element minOccurs="0" name="ChambersDescription" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="HearingSubTypeId" type="xs:int"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="SCCHHearingSubTypeDetails" nillable="true" type="tns:SCCHHearingSubTypeDetails"/>
    </xs:schema>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking">
      <xs:import namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects"/>
      <xs:complexType name="BookHearingInfo">
        <xs:sequence>
          <xs:element minOccurs="0" name="CEIS_Physical_File_ID" type="xs:decimal"/>
          <xs:element minOccurs="0" name="containerID" type="xs:int"/>
          <xs:element minOccurs="0" name="dateTime" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="hearingLength" type="xs:int"/>
          <xs:element minOccurs="0" name="hearingTypeId" type="xs:int"/>
          <xs:element minOccurs="0" name="locationID" type="xs:int"/>
          <xs:element minOccurs="0" name="requestedBy" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="BookHearingInfo" nillable="true" type="tns:BookHearingInfo"/>
      <xs:complexType name="BookingHearingResult">
        <xs:sequence>
          <xs:element minOccurs="0" name="bookingResult" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="BookingHearingResult" nillable="true" type="tns:BookingHearingResult"/>
      <xs:complexType name="CoABookingHearingInfo">
        <xs:sequence>
          <xs:element minOccurs="0" name="MainCase" type="xs:boolean"/>
          <xs:element minOccurs="0" name="RelatedCases" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="caseID" type="xs:int"/>
          <xs:element minOccurs="0" name="email" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="hearingDate" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="hearingLength" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="hearingTypeId" type="xs:int"/>
          <xs:element minOccurs="0" name="phone" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="requestedBy" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="CoABookingHearingInfo" nillable="true" type="tns:CoABookingHearingInfo"/>
      <xs:complexType name="CoAChambersBookingHearingInfo">
        <xs:sequence>
          <xs:element minOccurs="0" name="HearingTypeListID" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="MainCase" type="xs:boolean"/>
          <xs:element minOccurs="0" name="RelatedCases" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="caseID" type="xs:int"/>
          <xs:element minOccurs="0" name="email" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="hearingDate" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="hearingLength" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="phone" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="requestedBy" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="CoAChambersBookingHearingInfo" nillable="true" type="tns:CoAChambersBookingHearingInfo"/>
      <xs:complexType name="AvailableTrialDatesRequestInfo">
        <xs:sequence>
          <xs:element minOccurs="0" name="BookingLocationID" type="xs:int"/>
          <xs:element minOccurs="0" name="Courtclass" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="EndDate" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="FormulaType" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="HearingLength" type="xs:int"/>
          <xs:element minOccurs="0" name="HearingTypeId" type="xs:int"/>
          <xs:element minOccurs="0" name="LocationID" type="xs:int"/>
          <xs:element minOccurs="0" name="StartDate" type="xs:dateTime"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="AvailableTrialDatesRequestInfo" nillable="true" type="tns:AvailableTrialDatesRequestInfo"/>
      <xs:complexType name="AvailableTrialDatesResult">
        <xs:sequence>
          <xs:element xmlns:q1="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects" minOccurs="0" name="AvailableTrialDates" nillable="true" type="q1:AvailableTrialDates"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="AvailableTrialDatesResult" nillable="true" type="tns:AvailableTrialDatesResult"/>
      <xs:complexType name="BookTrialHearingInfo">
        <xs:sequence>
          <xs:element minOccurs="0" name="BookingLocationID" type="xs:int"/>
          <xs:element minOccurs="0" name="CEIS_Physical_File_ID" type="xs:decimal"/>
          <xs:element minOccurs="0" name="CourtClass" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="FormulaType" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="HearingDate" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="HearingLength" type="xs:int"/>
          <xs:element minOccurs="0" name="HearingType" type="xs:int"/>
          <xs:element minOccurs="0" name="LocationID" type="xs:int"/>
          <xs:element minOccurs="0" name="RequestedBy" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="SCJOB_Trial_Booking_Date" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="SCJOB_Trial_Booking_ID" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="BookTrialHearingInfo" nillable="true" type="tns:BookTrialHearingInfo"/>
      <xs:complexType name="BookingSCCHHearingInfo">
        <xs:sequence>
          <xs:element minOccurs="0" name="BookingLocationID" type="xs:int"/>
          <xs:element minOccurs="0" name="CEIS_Physical_File_ID" type="xs:decimal"/>
          <xs:element minOccurs="0" name="CourtClass" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="FormulaType" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="HearingDate" type="xs:dateTime"/>
          <xs:element minOccurs="0" name="HearingLength" type="xs:int"/>
          <xs:element minOccurs="0" name="HearingTypeId" type="xs:int"/>
          <xs:element minOccurs="0" name="LocationID" type="xs:int"/>
          <xs:element minOccurs="0" name="RequestedBy" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="BookingSCCHHearingInfo" nillable="true" type="tns:BookingSCCHHearingInfo"/>
    </xs:schema>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/Arrays" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
      <xs:complexType name="ArrayOfstring">
        <xs:sequence>
          <xs:element minOccurs="0" maxOccurs="unbounded" name="string" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ArrayOfstring" nillable="true" type="tns:ArrayOfstring"/>
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="IOnlineBooking_scCaseNumberValid_InputMessage">
    <wsdl:part name="parameters" element="tns:scCaseNumberValid"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_scCaseNumberValid_OutputMessage">
    <wsdl:part name="parameters" element="tns:scCaseNumberValidResponse"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_scGetLocations_InputMessage">
    <wsdl:part name="parameters" element="tns:scGetLocations"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_scGetLocations_OutputMessage">
    <wsdl:part name="parameters" element="tns:scGetLocationsResponse"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_scConfAvailableDatesByLocation_InputMessage">
    <wsdl:part name="parameters" element="tns:scConfAvailableDatesByLocation"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_scConfAvailableDatesByLocation_OutputMessage">
    <wsdl:part name="parameters" element="tns:scConfAvailableDatesByLocationResponse"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_scConfBookHearing_InputMessage">
    <wsdl:part name="parameters" element="tns:scConfBookHearing"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_scConfBookHearing_OutputMessage">
    <wsdl:part name="parameters" element="tns:scConfBookHearingResponse"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_coaCaseNumberValid_InputMessage">
    <wsdl:part name="parameters" element="tns:coaCaseNumberValid"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_coaCaseNumberValid_OutputMessage">
    <wsdl:part name="parameters" element="tns:coaCaseNumberValidResponse"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_coaAvailableAppealDates_InputMessage">
    <wsdl:part name="parameters" element="tns:coaAvailableAppealDates"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_coaAvailableAppealDates_OutputMessage">
    <wsdl:part name="parameters" element="tns:coaAvailableAppealDatesResponse"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_coaQueueAppealHearing_InputMessage">
    <wsdl:part name="parameters" element="tns:coaQueueAppealHearing"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_coaQueueAppealHearing_OutputMessage">
    <wsdl:part name="parameters" element="tns:coaQueueAppealHearingResponse"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_coaAvailableCHDates_InputMessage">
    <wsdl:part name="parameters" element="tns:coaAvailableCHDates"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_coaAvailableCHDates_OutputMessage">
    <wsdl:part name="parameters" element="tns:coaAvailableCHDatesResponse"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_coaQueueCHHearing_InputMessage">
    <wsdl:part name="parameters" element="tns:coaQueueCHHearing"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_coaQueueCHHearing_OutputMessage">
    <wsdl:part name="parameters" element="tns:coaQueueCHHearingResponse"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_coaCHApplicationList_InputMessage">
    <wsdl:part name="parameters" element="tns:coaCHApplicationList"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_coaCHApplicationList_OutputMessage">
    <wsdl:part name="parameters" element="tns:coaCHApplicationListResponse"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_scAvailableFormulasByHearingTypeAndLocation_InputMessage">
    <wsdl:part name="parameters" element="tns:scAvailableFormulasByHearingTypeAndLocation"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_scAvailableFormulasByHearingTypeAndLocation_OutputMessage">
    <wsdl:part name="parameters" element="tns:scAvailableFormulasByHearingTypeAndLocationResponse"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_scAvailableDatesByHearingTypeAndLocation_InputMessage">
    <wsdl:part name="parameters" element="tns:scAvailableDatesByHearingTypeAndLocation"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_scAvailableDatesByHearingTypeAndLocation_OutputMessage">
    <wsdl:part name="parameters" element="tns:scAvailableDatesByHearingTypeAndLocationResponse"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_scTrialBookHearing_InputMessage">
    <wsdl:part name="parameters" element="tns:scTrialBookHearing"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_scTrialBookHearing_OutputMessage">
    <wsdl:part name="parameters" element="tns:scTrialBookHearingResponse"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_scGetAvailableBookingTypes_InputMessage">
    <wsdl:part name="parameters" element="tns:scGetAvailableBookingTypes"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_scGetAvailableBookingTypes_OutputMessage">
    <wsdl:part name="parameters" element="tns:scGetAvailableBookingTypesResponse"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_scCHHearingSubType_InputMessage">
    <wsdl:part name="parameters" element="tns:scCHHearingSubType"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_scCHHearingSubType_OutputMessage">
    <wsdl:part name="parameters" element="tns:scCHHearingSubTypeResponse"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_scCHBookHearing_InputMessage">
    <wsdl:part name="parameters" element="tns:scCHBookHearing"/>
  </wsdl:message>
  <wsdl:message name="IOnlineBooking_scCHBookHearing_OutputMessage">
    <wsdl:part name="parameters" element="tns:scCHBookHearingResponse"/>
  </wsdl:message>
  <wsdl:portType name="IOnlineBooking">
    <wsdl:operation name="scCaseNumberValid">
      <wsdl:input wsaw:Action="http://tempuri.org/IOnlineBooking/scCaseNumberValid" message="tns:IOnlineBooking_scCaseNumberValid_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IOnlineBooking/scCaseNumberValidResponse" message="tns:IOnlineBooking_scCaseNumberValid_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="scGetLocations">
      <wsdl:input wsaw:Action="http://tempuri.org/IOnlineBooking/scGetLocations" message="tns:IOnlineBooking_scGetLocations_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IOnlineBooking/scGetLocationsResponse" message="tns:IOnlineBooking_scGetLocations_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="scConfAvailableDatesByLocation">
      <wsdl:input wsaw:Action="http://tempuri.org/IOnlineBooking/scConfAvailableDatesByLocation" message="tns:IOnlineBooking_scConfAvailableDatesByLocation_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IOnlineBooking/scConfAvailableDatesByLocationResponse" message="tns:IOnlineBooking_scConfAvailableDatesByLocation_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="scConfBookHearing">
      <wsdl:input wsaw:Action="http://tempuri.org/IOnlineBooking/scConfBookHearing" message="tns:IOnlineBooking_scConfBookHearing_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IOnlineBooking/scConfBookHearingResponse" message="tns:IOnlineBooking_scConfBookHearing_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="coaCaseNumberValid">
      <wsdl:input wsaw:Action="http://tempuri.org/IOnlineBooking/coaCaseNumberValid" message="tns:IOnlineBooking_coaCaseNumberValid_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IOnlineBooking/coaCaseNumberValidResponse" message="tns:IOnlineBooking_coaCaseNumberValid_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="coaAvailableAppealDates">
      <wsdl:input wsaw:Action="http://tempuri.org/IOnlineBooking/coaAvailableAppealDates" message="tns:IOnlineBooking_coaAvailableAppealDates_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IOnlineBooking/coaAvailableAppealDatesResponse" message="tns:IOnlineBooking_coaAvailableAppealDates_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="coaQueueAppealHearing">
      <wsdl:input wsaw:Action="http://tempuri.org/IOnlineBooking/coaQueueAppealHearing" message="tns:IOnlineBooking_coaQueueAppealHearing_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IOnlineBooking/coaQueueAppealHearingResponse" message="tns:IOnlineBooking_coaQueueAppealHearing_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="coaAvailableCHDates">
      <wsdl:input wsaw:Action="http://tempuri.org/IOnlineBooking/coaAvailableCHDates" message="tns:IOnlineBooking_coaAvailableCHDates_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IOnlineBooking/coaAvailableCHDatesResponse" message="tns:IOnlineBooking_coaAvailableCHDates_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="coaQueueCHHearing">
      <wsdl:input wsaw:Action="http://tempuri.org/IOnlineBooking/coaQueueCHHearing" message="tns:IOnlineBooking_coaQueueCHHearing_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IOnlineBooking/coaQueueCHHearingResponse" message="tns:IOnlineBooking_coaQueueCHHearing_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="coaCHApplicationList">
      <wsdl:input wsaw:Action="http://tempuri.org/IOnlineBooking/coaCHApplicationList" message="tns:IOnlineBooking_coaCHApplicationList_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IOnlineBooking/coaCHApplicationListResponse" message="tns:IOnlineBooking_coaCHApplicationList_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="scAvailableFormulasByHearingTypeAndLocation">
      <wsdl:input wsaw:Action="http://tempuri.org/IOnlineBooking/scAvailableFormulasByHearingTypeAndLocation" message="tns:IOnlineBooking_scAvailableFormulasByHearingTypeAndLocation_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IOnlineBooking/scAvailableFormulasByHearingTypeAndLocationResponse" message="tns:IOnlineBooking_scAvailableFormulasByHearingTypeAndLocation_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="scAvailableDatesByHearingTypeAndLocation">
      <wsdl:input wsaw:Action="http://tempuri.org/IOnlineBooking/scAvailableDatesByHearingTypeAndLocation" message="tns:IOnlineBooking_scAvailableDatesByHearingTypeAndLocation_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IOnlineBooking/scAvailableDatesByHearingTypeAndLocationResponse" message="tns:IOnlineBooking_scAvailableDatesByHearingTypeAndLocation_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="scTrialBookHearing">
      <wsdl:input wsaw:Action="http://tempuri.org/IOnlineBooking/scTrialBookHearing" message="tns:IOnlineBooking_scTrialBookHearing_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IOnlineBooking/scTrialBookHearingResponse" message="tns:IOnlineBooking_scTrialBookHearing_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="scGetAvailableBookingTypes">
      <wsdl:input wsaw:Action="http://tempuri.org/IOnlineBooking/scGetAvailableBookingTypes" message="tns:IOnlineBooking_scGetAvailableBookingTypes_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IOnlineBooking/scGetAvailableBookingTypesResponse" message="tns:IOnlineBooking_scGetAvailableBookingTypes_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="scCHHearingSubType">
      <wsdl:input wsaw:Action="http://tempuri.org/IOnlineBooking/scCHHearingSubType" message="tns:IOnlineBooking_scCHHearingSubType_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IOnlineBooking/scCHHearingSubTypeResponse" message="tns:IOnlineBooking_scCHHearingSubType_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="scCHBookHearing">
      <wsdl:input wsaw:Action="http://tempuri.org/IOnlineBooking/scCHBookHearing" message="tns:IOnlineBooking_scCHBookHearing_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IOnlineBooking/scCHBookHearingResponse" message="tns:IOnlineBooking_scCHBookHearing_OutputMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicHttpBinding_IOnlineBooking" type="tns:IOnlineBooking">
    <wsp:PolicyReference URI="#BasicHttpBinding_IOnlineBooking_policy"/>
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="scCaseNumberValid">
      <soap:operation soapAction="http://tempuri.org/IOnlineBooking/scCaseNumberValid" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="scGetLocations">
      <soap:operation soapAction="http://tempuri.org/IOnlineBooking/scGetLocations" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="scConfAvailableDatesByLocation">
      <soap:operation soapAction="http://tempuri.org/IOnlineBooking/scConfAvailableDatesByLocation" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="scConfBookHearing">
      <soap:operation soapAction="http://tempuri.org/IOnlineBooking/scConfBookHearing" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="coaCaseNumberValid">
      <soap:operation soapAction="http://tempuri.org/IOnlineBooking/coaCaseNumberValid" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="coaAvailableAppealDates">
      <soap:operation soapAction="http://tempuri.org/IOnlineBooking/coaAvailableAppealDates" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="coaQueueAppealHearing">
      <soap:operation soapAction="http://tempuri.org/IOnlineBooking/coaQueueAppealHearing" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="coaAvailableCHDates">
      <soap:operation soapAction="http://tempuri.org/IOnlineBooking/coaAvailableCHDates" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="coaQueueCHHearing">
      <soap:operation soapAction="http://tempuri.org/IOnlineBooking/coaQueueCHHearing" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="coaCHApplicationList">
      <soap:operation soapAction="http://tempuri.org/IOnlineBooking/coaCHApplicationList" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="scAvailableFormulasByHearingTypeAndLocation">
      <soap:operation soapAction="http://tempuri.org/IOnlineBooking/scAvailableFormulasByHearingTypeAndLocation" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="scAvailableDatesByHearingTypeAndLocation">
      <soap:operation soapAction="http://tempuri.org/IOnlineBooking/scAvailableDatesByHearingTypeAndLocation" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="scTrialBookHearing">
      <soap:operation soapAction="http://tempuri.org/IOnlineBooking/scTrialBookHearing" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="scGetAvailableBookingTypes">
      <soap:operation soapAction="http://tempuri.org/IOnlineBooking/scGetAvailableBookingTypes" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="scCHHearingSubType">
      <soap:operation soapAction="http://tempuri.org/IOnlineBooking/scCHHearingSubType" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="scCHBookHearing">
      <soap:operation soapAction="http://tempuri.org/IOnlineBooking/scCHBookHearing" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="OnlineBooking">
    <wsdl:port name="BasicHttpBinding_IOnlineBooking" binding="tns:BasicHttpBinding_IOnlineBooking">
      <soap:address location="https://localhost:8092/OnlineBooking.svc"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
