kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.taskrunner.componentName }}
  labels:
    component: {{ .Values.taskrunner.componentName }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"scj-booking-taskrunner-runtime:{{ .Values.images.taskrunner.tag }}","namespace":"bc7c5c-tools"},"fieldPath":"spec.template.spec.containers[?(@.name==\"taskrunner\")].image","pause":"false"}]
spec:
  selector:
    matchLabels:
      app: scj-booking
      component: {{ .Values.taskrunner.componentName }}
      release: {{ .Release.Name }}
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: scj-booking
        component: {{ .Values.taskrunner.componentName }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.taskrunner.componentName }}
          resources:
{{ toYaml .Values.taskrunner.resources | indent 12 }}
          image: {{ .Values.images.taskrunner.name }}:{{ .Values.images.taskrunner.tag }}
          imagePullPolicy: {{ .Values.taskrunner.imagePullPolicy }}
          terminationMessagePath: /dev/termination-log
          name: taskrunner
          env:
            - name: TAG_NAME
              value: {{ .Values.taskrunner.env.tagName }}
            - name: SC_MAIL_USERNAME
              value: {{ .Values.taskrunner.env.scMailUsername }}
            - name: CA_MAIL_USERNAME
              value: {{ .Values.taskrunner.env.caMailUsername }}
            - name: SC_EMAIL
              value: {{ .Values.taskrunner.env.scEmail }}
            - name: CA_EMAIL
              value: {{ .Values.taskrunner.env.caEmail }}
            - name: ConnectionString
              valueFrom:
                secretKeyRef:
                  name: {{ template "scjob_patroni_secrets" . }}
                  key: connect-string
            - name: TZ
              value: America/Vancouver
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-app-secrets
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - health.sh
            initialDelaySeconds: 120
            timeoutSeconds: 10
            periodSeconds: 120
            successThreshold: 1
            failureThreshold: 3
