//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCJ.SC.OnlineBooking
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class Location : object
    {
        
        private string locationCodeField;
        
        private int locationIDField;
        
        private string locationNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string locationCode
        {
            get
            {
                return this.locationCodeField;
            }
            set
            {
                this.locationCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int locationID
        {
            get
            {
                return this.locationIDField;
            }
            set
            {
                this.locationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string locationName
        {
            get
            {
                return this.locationNameField;
            }
            set
            {
                this.locationNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailableDatesByLocation", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class AvailableDatesByLocation : object
    {
        
        private SCJ.SC.OnlineBooking.ContainerInfo[] AvailableDatesField;
        
        private SCJ.SC.OnlineBooking.BookingDetail BookingDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SCJ.SC.OnlineBooking.ContainerInfo[] AvailableDates
        {
            get
            {
                return this.AvailableDatesField;
            }
            set
            {
                this.AvailableDatesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SCJ.SC.OnlineBooking.BookingDetail BookingDetails
        {
            get
            {
                return this.BookingDetailsField;
            }
            set
            {
                this.BookingDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingDetail", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class BookingDetail : object
    {
        
        private string bookingNotesField;
        
        private int detailBookingLengthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bookingNotes
        {
            get
            {
                return this.bookingNotesField;
            }
            set
            {
                this.bookingNotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int detailBookingLength
        {
            get
            {
                return this.detailBookingLengthField;
            }
            set
            {
                this.detailBookingLengthField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContainerInfo", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class ContainerInfo : object
    {
        
        private int ContainerIDField;
        
        private System.DateTime Date_TimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContainerID
        {
            get
            {
                return this.ContainerIDField;
            }
            set
            {
                this.ContainerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Time
        {
            get
            {
                return this.Date_TimeField;
            }
            set
            {
                this.Date_TimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookHearingInfo", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking")]
    public partial class BookHearingInfo : object
    {
        
        private int caseIDField;
        
        private int containerIDField;
        
        private System.DateTime dateTimeField;
        
        private int hearingLengthField;
        
        private int hearingTypeIdField;
        
        private int locationIDField;
        
        private string requestedByField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int caseID
        {
            get
            {
                return this.caseIDField;
            }
            set
            {
                this.caseIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int containerID
        {
            get
            {
                return this.containerIDField;
            }
            set
            {
                this.containerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateTime
        {
            get
            {
                return this.dateTimeField;
            }
            set
            {
                this.dateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int hearingLength
        {
            get
            {
                return this.hearingLengthField;
            }
            set
            {
                this.hearingLengthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int hearingTypeId
        {
            get
            {
                return this.hearingTypeIdField;
            }
            set
            {
                this.hearingTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int locationID
        {
            get
            {
                return this.locationIDField;
            }
            set
            {
                this.locationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string requestedBy
        {
            get
            {
                return this.requestedByField;
            }
            set
            {
                this.requestedByField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingHearingResult", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking")]
    public partial class BookingHearingResult : object
    {
        
        private string bookingResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bookingResult
        {
            get
            {
                return this.bookingResultField;
            }
            set
            {
                this.bookingResultField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SCJ.SC.OnlineBooking.IOnlineBooking")]
    public interface IOnlineBooking
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/caseNumberValid", ReplyAction="http://tempuri.org/IOnlineBooking/caseNumberValidResponse")]
        System.Threading.Tasks.Task<int> caseNumberValidAsync(string caseNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/getLocations", ReplyAction="http://tempuri.org/IOnlineBooking/getLocationsResponse")]
        System.Threading.Tasks.Task<SCJ.SC.OnlineBooking.Location[]> getLocationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/AvailableDatesByLocation", ReplyAction="http://tempuri.org/IOnlineBooking/AvailableDatesByLocationResponse")]
        System.Threading.Tasks.Task<SCJ.SC.OnlineBooking.AvailableDatesByLocation> AvailableDatesByLocationAsync(int locationID, int hearingTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/BookingHearing", ReplyAction="http://tempuri.org/IOnlineBooking/BookingHearingResponse")]
        System.Threading.Tasks.Task<SCJ.SC.OnlineBooking.BookingHearingResult> BookingHearingAsync(SCJ.SC.OnlineBooking.BookHearingInfo bookInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IOnlineBookingChannel : SCJ.SC.OnlineBooking.IOnlineBooking, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class OnlineBookingClient : System.ServiceModel.ClientBase<SCJ.SC.OnlineBooking.IOnlineBooking>, SCJ.SC.OnlineBooking.IOnlineBooking
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OnlineBookingClient() : 
                base(OnlineBookingClient.GetDefaultBinding(), OnlineBookingClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IOnlineBooking.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnlineBookingClient(EndpointConfiguration endpointConfiguration) : 
                base(OnlineBookingClient.GetBindingForEndpoint(endpointConfiguration), OnlineBookingClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnlineBookingClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OnlineBookingClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnlineBookingClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OnlineBookingClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnlineBookingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }



        
        public System.Threading.Tasks.Task<int> caseNumberValidAsync(string caseNum)
        {
            return base.Channel.caseNumberValidAsync(caseNum);
        }
        
        public System.Threading.Tasks.Task<SCJ.SC.OnlineBooking.Location[]> getLocationsAsync()
        {
            return base.Channel.getLocationsAsync();
        }
        
        public System.Threading.Tasks.Task<SCJ.SC.OnlineBooking.AvailableDatesByLocation> AvailableDatesByLocationAsync(int locationID, int hearingTypeID)
        {
            return base.Channel.AvailableDatesByLocationAsync(locationID, hearingTypeID);
        }
        
        public System.Threading.Tasks.Task<SCJ.SC.OnlineBooking.BookingHearingResult> BookingHearingAsync(SCJ.SC.OnlineBooking.BookHearingInfo bookInfo)
        {
            return base.Channel.BookingHearingAsync(bookInfo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOnlineBooking))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOnlineBooking))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:8092/OnlineBooking.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OnlineBookingClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IOnlineBooking);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OnlineBookingClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IOnlineBooking);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IOnlineBooking,
        }
    }
}
