images:
  app:
    tag: test

app:
  env:
    environment: test
  # use the test.justice.gov.bc.ca reverse proxy IP list, but to not commit to source control
  allowedIPs: 1.2.3.4

patroni:
  replicas: 1

backup:
  enabled: true
