images:
  app:
    tag: prod

app:
  env:
    environment: prod
  # use the justice.gov.bc.ca reverse proxy IP list, but to not commit to source control
  allowedIPs: 1.2.3.4

patroni:
  replicas: 3

backup:
  enabled: true

  enironment:
    friendlyName: "SCJOB Postgres Backup [prod]"
    name: "bc7c5c-prod"

