//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCJ.OnlineBooking
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourtFile", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class CourtFile : object
    {

        private System.Nullable<decimal> CEISLocationIdField;

        private string courtClassCodeField;

        private string courtFileNumberField;

        private string courtLevelCodeField;

        private int fairUseSortField;

        private bool futureTrialHearingField;

        private System.Nullable<decimal> physicalFileIdField;

        private string styleOfCauseField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CEISLocationId
        {
            get
            {
                return this.CEISLocationIdField;
            }
            set
            {
                this.CEISLocationIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string courtClassCode
        {
            get
            {
                return this.courtClassCodeField;
            }
            set
            {
                this.courtClassCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string courtFileNumber
        {
            get
            {
                return this.courtFileNumberField;
            }
            set
            {
                this.courtFileNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string courtLevelCode
        {
            get
            {
                return this.courtLevelCodeField;
            }
            set
            {
                this.courtLevelCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fairUseSort
        {
            get
            {
                return this.fairUseSortField;
            }
            set
            {
                this.fairUseSortField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool futureTrialHearing
        {
            get
            {
                return this.futureTrialHearingField;
            }
            set
            {
                this.futureTrialHearingField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> physicalFileId
        {
            get
            {
                return this.physicalFileIdField;
            }
            set
            {
                this.physicalFileIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string styleOfCause
        {
            get
            {
                return this.styleOfCauseField;
            }
            set
            {
                this.styleOfCauseField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class Location : object
    {

        private int bookingHearingTypeIDField;

        private int bookingLocationIDField;

        private string locationCodeField;

        private int locationIDField;

        private string locationNameField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bookingHearingTypeID
        {
            get
            {
                return this.bookingHearingTypeIDField;
            }
            set
            {
                this.bookingHearingTypeIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bookingLocationID
        {
            get
            {
                return this.bookingLocationIDField;
            }
            set
            {
                this.bookingLocationIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string locationCode
        {
            get
            {
                return this.locationCodeField;
            }
            set
            {
                this.locationCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int locationID
        {
            get
            {
                return this.locationIDField;
            }
            set
            {
                this.locationIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string locationName
        {
            get
            {
                return this.locationNameField;
            }
            set
            {
                this.locationNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailableDatesByLocation", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class AvailableDatesByLocation : object
    {

        private SCJ.OnlineBooking.ContainerInfo[] AvailableDatesField;

        private SCJ.OnlineBooking.BookingDetail BookingDetailsField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SCJ.OnlineBooking.ContainerInfo[] AvailableDates
        {
            get
            {
                return this.AvailableDatesField;
            }
            set
            {
                this.AvailableDatesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SCJ.OnlineBooking.BookingDetail BookingDetails
        {
            get
            {
                return this.BookingDetailsField;
            }
            set
            {
                this.BookingDetailsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingDetail", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class BookingDetail : object
    {

        private string bookingNotesField;

        private int detailBookingLengthField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bookingNotes
        {
            get
            {
                return this.bookingNotesField;
            }
            set
            {
                this.bookingNotesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int detailBookingLength
        {
            get
            {
                return this.detailBookingLengthField;
            }
            set
            {
                this.detailBookingLengthField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContainerInfo", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class ContainerInfo : object
    {

        private int ContainerIDField;

        private System.DateTime Date_TimeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContainerID
        {
            get
            {
                return this.ContainerIDField;
            }
            set
            {
                this.ContainerIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Time
        {
            get
            {
                return this.Date_TimeField;
            }
            set
            {
                this.Date_TimeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookHearingInfo", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking")]
    public partial class BookHearingInfo : object
    {

        private decimal CEIS_Physical_File_IDField;

        private int containerIDField;

        private System.DateTime dateTimeField;

        private int hearingLengthField;

        private int hearingTypeIdField;

        private int locationIDField;

        private string requestedByField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CEIS_Physical_File_ID
        {
            get
            {
                return this.CEIS_Physical_File_IDField;
            }
            set
            {
                this.CEIS_Physical_File_IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int containerID
        {
            get
            {
                return this.containerIDField;
            }
            set
            {
                this.containerIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateTime
        {
            get
            {
                return this.dateTimeField;
            }
            set
            {
                this.dateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int hearingLength
        {
            get
            {
                return this.hearingLengthField;
            }
            set
            {
                this.hearingLengthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int hearingTypeId
        {
            get
            {
                return this.hearingTypeIdField;
            }
            set
            {
                this.hearingTypeIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int locationID
        {
            get
            {
                return this.locationIDField;
            }
            set
            {
                this.locationIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string requestedBy
        {
            get
            {
                return this.requestedByField;
            }
            set
            {
                this.requestedByField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingHearingResult", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking")]
    public partial class BookingHearingResult : object
    {

        private string bookingResultField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bookingResult
        {
            get
            {
                return this.bookingResultField;
            }
            set
            {
                this.bookingResultField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="COACaseList", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class COACaseList : object
    {

        private SCJ.OnlineBooking.CoAClassInfo[] CaseListField;

        private string CaseTypeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SCJ.OnlineBooking.CoAClassInfo[] CaseList
        {
            get
            {
                return this.CaseListField;
            }
            set
            {
                this.CaseListField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CaseType
        {
            get
            {
                return this.CaseTypeField;
            }
            set
            {
                this.CaseTypeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CoAClassInfo", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class CoAClassInfo : object
    {

        private int CaseIdField;

        private string Case_NumField;

        private bool MainField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CaseId
        {
            get
            {
                return this.CaseIdField;
            }
            set
            {
                this.CaseIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Case_Num
        {
            get
            {
                return this.Case_NumField;
            }
            set
            {
                this.Case_NumField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Main
        {
            get
            {
                return this.MainField;
            }
            set
            {
                this.MainField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CoAAvailableDates", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class CoAAvailableDates : object
    {

        private SCJ.OnlineBooking.ShedulesInfo[] AvailableDatesField;

        private string BookingNotesField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SCJ.OnlineBooking.ShedulesInfo[] AvailableDates
        {
            get
            {
                return this.AvailableDatesField;
            }
            set
            {
                this.AvailableDatesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookingNotes
        {
            get
            {
                return this.BookingNotesField;
            }
            set
            {
                this.BookingNotesField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShedulesInfo", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class ShedulesInfo : object
    {

        private string availabilityField;

        private System.DateTime scheduleDateField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string availability
        {
            get
            {
                return this.availabilityField;
            }
            set
            {
                this.availabilityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime scheduleDate
        {
            get
            {
                return this.scheduleDateField;
            }
            set
            {
                this.scheduleDateField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CoABookingHearingInfo", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking")]
    public partial class CoABookingHearingInfo : object
    {

        private bool MainCaseField;

        private string RelatedCasesField;

        private int caseIDField;

        private string emailField;

        private System.DateTime hearingDateField;

        private string hearingLengthField;

        private int hearingTypeIdField;

        private string phoneField;

        private string requestedByField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MainCase
        {
            get
            {
                return this.MainCaseField;
            }
            set
            {
                this.MainCaseField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelatedCases
        {
            get
            {
                return this.RelatedCasesField;
            }
            set
            {
                this.RelatedCasesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int caseID
        {
            get
            {
                return this.caseIDField;
            }
            set
            {
                this.caseIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime hearingDate
        {
            get
            {
                return this.hearingDateField;
            }
            set
            {
                this.hearingDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hearingLength
        {
            get
            {
                return this.hearingLengthField;
            }
            set
            {
                this.hearingLengthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int hearingTypeId
        {
            get
            {
                return this.hearingTypeIdField;
            }
            set
            {
                this.hearingTypeIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string requestedBy
        {
            get
            {
                return this.requestedByField;
            }
            set
            {
                this.requestedByField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CoAChambersAvailableDates", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class CoAChambersAvailableDates : object
    {

        private SCJ.OnlineBooking.CoAChambersShedulesInfo[] AvailableDatesField;

        private string BookingNotesField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SCJ.OnlineBooking.CoAChambersShedulesInfo[] AvailableDates
        {
            get
            {
                return this.AvailableDatesField;
            }
            set
            {
                this.AvailableDatesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookingNotes
        {
            get
            {
                return this.BookingNotesField;
            }
            set
            {
                this.BookingNotesField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CoAChambersShedulesInfo", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class CoAChambersShedulesInfo : object
    {

        private string availabilityField;

        private System.DateTime scheduleDateField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string availability
        {
            get
            {
                return this.availabilityField;
            }
            set
            {
                this.availabilityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime scheduleDate
        {
            get
            {
                return this.scheduleDateField;
            }
            set
            {
                this.scheduleDateField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CoAChambersBookingHearingInfo", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking")]
    public partial class CoAChambersBookingHearingInfo : object
    {

        private string HearingTypeListIDField;

        private bool MainCaseField;

        private string RelatedCasesField;

        private int caseIDField;

        private string emailField;

        private System.DateTime hearingDateField;

        private string hearingLengthField;

        private string phoneField;

        private string requestedByField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HearingTypeListID
        {
            get
            {
                return this.HearingTypeListIDField;
            }
            set
            {
                this.HearingTypeListIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MainCase
        {
            get
            {
                return this.MainCaseField;
            }
            set
            {
                this.MainCaseField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RelatedCases
        {
            get
            {
                return this.RelatedCasesField;
            }
            set
            {
                this.RelatedCasesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int caseID
        {
            get
            {
                return this.caseIDField;
            }
            set
            {
                this.caseIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime hearingDate
        {
            get
            {
                return this.hearingDateField;
            }
            set
            {
                this.hearingDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hearingLength
        {
            get
            {
                return this.hearingLengthField;
            }
            set
            {
                this.hearingLengthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string requestedBy
        {
            get
            {
                return this.requestedByField;
            }
            set
            {
                this.requestedByField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CoAChambersApplications", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class CoAChambersApplications : object
    {

        private string ApplicationTypeDefinitionField;

        private string ApplicationTypeNameField;

        private int HearingTypeIDField;

        private string TimelineField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationTypeDefinition
        {
            get
            {
                return this.ApplicationTypeDefinitionField;
            }
            set
            {
                this.ApplicationTypeDefinitionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationTypeName
        {
            get
            {
                return this.ApplicationTypeNameField;
            }
            set
            {
                this.ApplicationTypeNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HearingTypeID
        {
            get
            {
                return this.HearingTypeIDField;
            }
            set
            {
                this.HearingTypeIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Timeline
        {
            get
            {
                return this.TimelineField;
            }
            set
            {
                this.TimelineField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormulaLocation", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class FormulaLocation : object
    {

        private string BookingHearingCodeField;

        private int BookingLocationIDField;

        private System.DateTime EndDateField;

        private System.Nullable<System.DateTime> FairUseBookingPeriodEndDateField;

        private System.Nullable<System.DateTime> FairUseBookingPeriodStartDateField;

        private System.Nullable<System.DateTime> FairUseContactDateField;

        private string FormulaTypeField;

        private int HearingTypeIdField;

        private string LocationCodeField;

        private int LocationIDField;

        private string LocationNameField;

        private System.DateTime StartDateField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookingHearingCode
        {
            get
            {
                return this.BookingHearingCodeField;
            }
            set
            {
                this.BookingHearingCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookingLocationID
        {
            get
            {
                return this.BookingLocationIDField;
            }
            set
            {
                this.BookingLocationIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FairUseBookingPeriodEndDate
        {
            get
            {
                return this.FairUseBookingPeriodEndDateField;
            }
            set
            {
                this.FairUseBookingPeriodEndDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FairUseBookingPeriodStartDate
        {
            get
            {
                return this.FairUseBookingPeriodStartDateField;
            }
            set
            {
                this.FairUseBookingPeriodStartDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FairUseContactDate
        {
            get
            {
                return this.FairUseContactDateField;
            }
            set
            {
                this.FairUseContactDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormulaType
        {
            get
            {
                return this.FormulaTypeField;
            }
            set
            {
                this.FormulaTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HearingTypeId
        {
            get
            {
                return this.HearingTypeIdField;
            }
            set
            {
                this.HearingTypeIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationCode
        {
            get
            {
                return this.LocationCodeField;
            }
            set
            {
                this.LocationCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationID
        {
            get
            {
                return this.LocationIDField;
            }
            set
            {
                this.LocationIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName
        {
            get
            {
                return this.LocationNameField;
            }
            set
            {
                this.LocationNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailableTrialDatesRequestInfo", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking")]
    public partial class AvailableTrialDatesRequestInfo : object
    {

        private int BookingLocationIDField;

        private string CourtclassField;

        private System.DateTime EndDateField;

        private string FormulaTypeField;

        private int HearingLengthField;

        private int HearingTypeIdField;

        private int LocationIDField;

        private System.DateTime StartDateField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookingLocationID
        {
            get
            {
                return this.BookingLocationIDField;
            }
            set
            {
                this.BookingLocationIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Courtclass
        {
            get
            {
                return this.CourtclassField;
            }
            set
            {
                this.CourtclassField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormulaType
        {
            get
            {
                return this.FormulaTypeField;
            }
            set
            {
                this.FormulaTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HearingLength
        {
            get
            {
                return this.HearingLengthField;
            }
            set
            {
                this.HearingLengthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HearingTypeId
        {
            get
            {
                return this.HearingTypeIdField;
            }
            set
            {
                this.HearingTypeIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationID
        {
            get
            {
                return this.LocationIDField;
            }
            set
            {
                this.LocationIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailableTrialDatesResult", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking")]
    public partial class AvailableTrialDatesResult : object
    {

        private SCJ.OnlineBooking.AvailableTrialDates AvailableTrialDatesField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SCJ.OnlineBooking.AvailableTrialDates AvailableTrialDates
        {
            get
            {
                return this.AvailableTrialDatesField;
            }
            set
            {
                this.AvailableTrialDatesField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailableTrialDates", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class AvailableTrialDates : object
    {

        private SCJ.OnlineBooking.AvailableTrialDatesInfo[] AvailablesDatesInfoField;

        private string BookingHearingCodeField;

        private int BookingLocationIDField;

        private string FormulaTypeField;

        private string LocationCodeField;

        private int LocationIDField;

        private string LocationNameField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public SCJ.OnlineBooking.AvailableTrialDatesInfo[] AvailablesDatesInfo
        {
            get
            {
                return this.AvailablesDatesInfoField;
            }
            set
            {
                this.AvailablesDatesInfoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookingHearingCode
        {
            get
            {
                return this.BookingHearingCodeField;
            }
            set
            {
                this.BookingHearingCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookingLocationID
        {
            get
            {
                return this.BookingLocationIDField;
            }
            set
            {
                this.BookingLocationIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormulaType
        {
            get
            {
                return this.FormulaTypeField;
            }
            set
            {
                this.FormulaTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationCode
        {
            get
            {
                return this.LocationCodeField;
            }
            set
            {
                this.LocationCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationID
        {
            get
            {
                return this.LocationIDField;
            }
            set
            {
                this.LocationIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName
        {
            get
            {
                return this.LocationNameField;
            }
            set
            {
                this.LocationNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailableTrialDatesInfo", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class AvailableTrialDatesInfo : object
    {

        private System.DateTime AvailableDateField;

        private int AvailableQuantityField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AvailableDate
        {
            get
            {
                return this.AvailableDateField;
            }
            set
            {
                this.AvailableDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvailableQuantity
        {
            get
            {
                return this.AvailableQuantityField;
            }
            set
            {
                this.AvailableQuantityField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookTrialHearingInfo", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking")]
    public partial class BookTrialHearingInfo : object
    {

        private int BookingLocationIDField;

        private decimal CEIS_Physical_File_IDField;

        private string CourtClassField;

        private string FormulaTypeField;

        private System.DateTime HearingDateField;

        private int HearingLengthField;

        private int HearingTypeField;

        private int LocationIDField;

        private string RequestedByField;

        private System.DateTime SCJOB_Trial_Booking_DateField;

        private string SCJOB_Trial_Booking_IDField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookingLocationID
        {
            get
            {
                return this.BookingLocationIDField;
            }
            set
            {
                this.BookingLocationIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CEIS_Physical_File_ID
        {
            get
            {
                return this.CEIS_Physical_File_IDField;
            }
            set
            {
                this.CEIS_Physical_File_IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourtClass
        {
            get
            {
                return this.CourtClassField;
            }
            set
            {
                this.CourtClassField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormulaType
        {
            get
            {
                return this.FormulaTypeField;
            }
            set
            {
                this.FormulaTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HearingDate
        {
            get
            {
                return this.HearingDateField;
            }
            set
            {
                this.HearingDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HearingLength
        {
            get
            {
                return this.HearingLengthField;
            }
            set
            {
                this.HearingLengthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HearingType
        {
            get
            {
                return this.HearingTypeField;
            }
            set
            {
                this.HearingTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationID
        {
            get
            {
                return this.LocationIDField;
            }
            set
            {
                this.LocationIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestedBy
        {
            get
            {
                return this.RequestedByField;
            }
            set
            {
                this.RequestedByField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SCJOB_Trial_Booking_Date
        {
            get
            {
                return this.SCJOB_Trial_Booking_DateField;
            }
            set
            {
                this.SCJOB_Trial_Booking_DateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SCJOB_Trial_Booking_ID
        {
            get
            {
                return this.SCJOB_Trial_Booking_IDField;
            }
            set
            {
                this.SCJOB_Trial_Booking_IDField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SCCHHearingSubTypeDetails", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking.Objects")]
    public partial class SCCHHearingSubTypeDetails : object
    {

        private string ChambersDescriptionField;

        private int HearingSubTypeIdField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChambersDescription
        {
            get
            {
                return this.ChambersDescriptionField;
            }
            set
            {
                this.ChambersDescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HearingSubTypeId
        {
            get
            {
                return this.HearingSubTypeIdField;
            }
            set
            {
                this.HearingSubTypeIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingSCCHHearingInfo", Namespace="http://schemas.datacontract.org/2004/07/SCSSOnlineBooking")]
    public partial class BookingSCCHHearingInfo : object
    {

        private int BookingLocationIDField;

        private decimal CEIS_Physical_File_IDField;

        private string CourtClassField;

        private string FormulaTypeField;

        private System.DateTime HearingDateField;

        private int HearingLengthField;

        private int HearingTypeIdField;

        private int LocationIDField;

        private string RequestedByField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookingLocationID
        {
            get
            {
                return this.BookingLocationIDField;
            }
            set
            {
                this.BookingLocationIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CEIS_Physical_File_ID
        {
            get
            {
                return this.CEIS_Physical_File_IDField;
            }
            set
            {
                this.CEIS_Physical_File_IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CourtClass
        {
            get
            {
                return this.CourtClassField;
            }
            set
            {
                this.CourtClassField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormulaType
        {
            get
            {
                return this.FormulaTypeField;
            }
            set
            {
                this.FormulaTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HearingDate
        {
            get
            {
                return this.HearingDateField;
            }
            set
            {
                this.HearingDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HearingLength
        {
            get
            {
                return this.HearingLengthField;
            }
            set
            {
                this.HearingLengthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HearingTypeId
        {
            get
            {
                return this.HearingTypeIdField;
            }
            set
            {
                this.HearingTypeIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationID
        {
            get
            {
                return this.LocationIDField;
            }
            set
            {
                this.LocationIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestedBy
        {
            get
            {
                return this.RequestedByField;
            }
            set
            {
                this.RequestedByField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SCJ.OnlineBooking.IOnlineBooking")]
    public interface IOnlineBooking
    {

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/scCaseNumberValid", ReplyAction="http://tempuri.org/IOnlineBooking/scCaseNumberValidResponse")]
        System.Threading.Tasks.Task<SCJ.OnlineBooking.CourtFile[]> scCaseNumberValidAsync(string caseNum);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/scGetLocations", ReplyAction="http://tempuri.org/IOnlineBooking/scGetLocationsResponse")]
        System.Threading.Tasks.Task<SCJ.OnlineBooking.Location[]> scGetLocationsAsync();

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/scConfAvailableDatesByLocation", ReplyAction="http://tempuri.org/IOnlineBooking/scConfAvailableDatesByLocationResponse")]
        System.Threading.Tasks.Task<SCJ.OnlineBooking.AvailableDatesByLocation> scConfAvailableDatesByLocationAsync(int locationID, int hearingTypeID);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/scConfBookHearing", ReplyAction="http://tempuri.org/IOnlineBooking/scConfBookHearingResponse")]
        System.Threading.Tasks.Task<SCJ.OnlineBooking.BookingHearingResult> scConfBookHearingAsync(SCJ.OnlineBooking.BookHearingInfo bookInfo);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/coaCaseNumberValid", ReplyAction="http://tempuri.org/IOnlineBooking/coaCaseNumberValidResponse")]
        System.Threading.Tasks.Task<SCJ.OnlineBooking.COACaseList> coaCaseNumberValidAsync(string caseNum);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/coaAvailableAppealDates", ReplyAction="http://tempuri.org/IOnlineBooking/coaAvailableAppealDatesResponse")]
        System.Threading.Tasks.Task<SCJ.OnlineBooking.CoAAvailableDates> coaAvailableAppealDatesAsync();

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/coaQueueAppealHearing", ReplyAction="http://tempuri.org/IOnlineBooking/coaQueueAppealHearingResponse")]
        System.Threading.Tasks.Task<SCJ.OnlineBooking.BookingHearingResult> coaQueueAppealHearingAsync(SCJ.OnlineBooking.CoABookingHearingInfo bookingInfo);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/coaAvailableCHDates", ReplyAction="http://tempuri.org/IOnlineBooking/coaAvailableCHDatesResponse")]
        System.Threading.Tasks.Task<SCJ.OnlineBooking.CoAChambersAvailableDates> coaAvailableCHDatesAsync();

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/coaQueueCHHearing", ReplyAction="http://tempuri.org/IOnlineBooking/coaQueueCHHearingResponse")]
        System.Threading.Tasks.Task<SCJ.OnlineBooking.BookingHearingResult> coaQueueCHHearingAsync(SCJ.OnlineBooking.CoAChambersBookingHearingInfo bookingInfo);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/coaCHApplicationList", ReplyAction="http://tempuri.org/IOnlineBooking/coaCHApplicationListResponse")]
        System.Threading.Tasks.Task<SCJ.OnlineBooking.CoAChambersApplications[]> coaCHApplicationListAsync(string type);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/scAvailableFormulasByHearingTypeAndLocation", ReplyAction="http://tempuri.org/IOnlineBooking/scAvailableFormulasByHearingTypeAndLocationResp" +
            "onse")]
        System.Threading.Tasks.Task<SCJ.OnlineBooking.FormulaLocation[]> scAvailableFormulasByHearingTypeAndLocationAsync(string locationID, string formula, string hearingTypeId);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/scAvailableDatesByHearingTypeAndLocation", ReplyAction="http://tempuri.org/IOnlineBooking/scAvailableDatesByHearingTypeAndLocationRespons" +
            "e")]
        System.Threading.Tasks.Task<SCJ.OnlineBooking.AvailableTrialDatesResult> scAvailableDatesByHearingTypeAndLocationAsync(SCJ.OnlineBooking.AvailableTrialDatesRequestInfo requestInfo);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/scTrialBookHearing", ReplyAction="http://tempuri.org/IOnlineBooking/scTrialBookHearingResponse")]
        System.Threading.Tasks.Task<SCJ.OnlineBooking.BookingHearingResult> scTrialBookHearingAsync(SCJ.OnlineBooking.BookTrialHearingInfo bookingInfo);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/scGetAvailableBookingTypes", ReplyAction="http://tempuri.org/IOnlineBooking/scGetAvailableBookingTypesResponse")]
        System.Threading.Tasks.Task<string[]> scGetAvailableBookingTypesAsync();

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/scCHHearingSubType", ReplyAction="http://tempuri.org/IOnlineBooking/scCHHearingSubTypeResponse")]
        System.Threading.Tasks.Task<SCJ.OnlineBooking.SCCHHearingSubTypeDetails[]> scCHHearingSubTypeAsync();

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnlineBooking/scCHBookHearing", ReplyAction="http://tempuri.org/IOnlineBooking/scCHBookHearingResponse")]
        System.Threading.Tasks.Task<SCJ.OnlineBooking.BookingHearingResult> scCHBookHearingAsync(SCJ.OnlineBooking.BookingSCCHHearingInfo bookInfo);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IOnlineBookingChannel : SCJ.OnlineBooking.IOnlineBooking, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class OnlineBookingClient : System.ServiceModel.ClientBase<SCJ.OnlineBooking.IOnlineBooking>, SCJ.OnlineBooking.IOnlineBooking
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public OnlineBookingClient() :
                base(OnlineBookingClient.GetDefaultBinding(), OnlineBookingClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IOnlineBooking.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public OnlineBookingClient(EndpointConfiguration endpointConfiguration) :
                base(OnlineBookingClient.GetBindingForEndpoint(endpointConfiguration), OnlineBookingClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public OnlineBookingClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(OnlineBookingClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public OnlineBookingClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(OnlineBookingClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public OnlineBookingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<SCJ.OnlineBooking.CourtFile[]> scCaseNumberValidAsync(string caseNum)
        {
            return base.Channel.scCaseNumberValidAsync(caseNum);
        }

        public System.Threading.Tasks.Task<SCJ.OnlineBooking.Location[]> scGetLocationsAsync()
        {
            return base.Channel.scGetLocationsAsync();
        }

        public System.Threading.Tasks.Task<SCJ.OnlineBooking.AvailableDatesByLocation> scConfAvailableDatesByLocationAsync(int locationID, int hearingTypeID)
        {
            return base.Channel.scConfAvailableDatesByLocationAsync(locationID, hearingTypeID);
        }

        public System.Threading.Tasks.Task<SCJ.OnlineBooking.BookingHearingResult> scConfBookHearingAsync(SCJ.OnlineBooking.BookHearingInfo bookInfo)
        {
            return base.Channel.scConfBookHearingAsync(bookInfo);
        }

        public System.Threading.Tasks.Task<SCJ.OnlineBooking.COACaseList> coaCaseNumberValidAsync(string caseNum)
        {
            return base.Channel.coaCaseNumberValidAsync(caseNum);
        }

        public System.Threading.Tasks.Task<SCJ.OnlineBooking.CoAAvailableDates> coaAvailableAppealDatesAsync()
        {
            return base.Channel.coaAvailableAppealDatesAsync();
        }

        public System.Threading.Tasks.Task<SCJ.OnlineBooking.BookingHearingResult> coaQueueAppealHearingAsync(SCJ.OnlineBooking.CoABookingHearingInfo bookingInfo)
        {
            return base.Channel.coaQueueAppealHearingAsync(bookingInfo);
        }

        public System.Threading.Tasks.Task<SCJ.OnlineBooking.CoAChambersAvailableDates> coaAvailableCHDatesAsync()
        {
            return base.Channel.coaAvailableCHDatesAsync();
        }

        public System.Threading.Tasks.Task<SCJ.OnlineBooking.BookingHearingResult> coaQueueCHHearingAsync(SCJ.OnlineBooking.CoAChambersBookingHearingInfo bookingInfo)
        {
            return base.Channel.coaQueueCHHearingAsync(bookingInfo);
        }

        public System.Threading.Tasks.Task<SCJ.OnlineBooking.CoAChambersApplications[]> coaCHApplicationListAsync(string type)
        {
            return base.Channel.coaCHApplicationListAsync(type);
        }

        public System.Threading.Tasks.Task<SCJ.OnlineBooking.FormulaLocation[]> scAvailableFormulasByHearingTypeAndLocationAsync(string locationID, string formula, string hearingTypeId)
        {
            return base.Channel.scAvailableFormulasByHearingTypeAndLocationAsync(locationID, formula, hearingTypeId);
        }

        public System.Threading.Tasks.Task<SCJ.OnlineBooking.AvailableTrialDatesResult> scAvailableDatesByHearingTypeAndLocationAsync(SCJ.OnlineBooking.AvailableTrialDatesRequestInfo requestInfo)
        {
            return base.Channel.scAvailableDatesByHearingTypeAndLocationAsync(requestInfo);
        }

        public System.Threading.Tasks.Task<SCJ.OnlineBooking.BookingHearingResult> scTrialBookHearingAsync(SCJ.OnlineBooking.BookTrialHearingInfo bookingInfo)
        {
            return base.Channel.scTrialBookHearingAsync(bookingInfo);
        }

        public System.Threading.Tasks.Task<string[]> scGetAvailableBookingTypesAsync()
        {
            return base.Channel.scGetAvailableBookingTypesAsync();
        }

        public System.Threading.Tasks.Task<SCJ.OnlineBooking.SCCHHearingSubTypeDetails[]> scCHHearingSubTypeAsync()
        {
            return base.Channel.scCHHearingSubTypeAsync();
        }

        public System.Threading.Tasks.Task<SCJ.OnlineBooking.BookingHearingResult> scCHBookHearingAsync(SCJ.OnlineBooking.BookingSCCHHearingInfo bookInfo)
        {
            return base.Channel.scCHBookHearingAsync(bookInfo);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOnlineBooking))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOnlineBooking))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:8092/OnlineBooking.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OnlineBookingClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IOnlineBooking);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OnlineBookingClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IOnlineBooking);
        }

        public enum EndpointConfiguration
        {

            BasicHttpBinding_IOnlineBooking,
        }
    }
}
