{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-app-secrets" .Release.Name)) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-app-secrets
  labels:
    component: {{ .Values.app.componentName }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
stringData:
  API_PASSWORD: ""
  EXCHANGE_CLIENT_SECRET: ""
  SC_MAIL_PASSWORD: ""
  CA_MAIL_PASSWORD: ""
  API_ENDPOINT: ""
  EXCHANGE_CLIENT_ID: ""
  EXCHANGE_TENANT_ID: ""
  API_USERNAME: ""
{{- end -}}