{{- $random_patroni_replication_password := randAlphaNum 20 }}
{{- $random_patroni_superuser_password := randAlphaNum 20 }}
{{- $random_patroni_app_user := randAlphaNum 3 }}
{{- $random_patroni_app_password := randAlphaNum 20 }}
{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-patroni-secrets" .Release.Name)) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-patroni-secrets
  labels:
    component: {{ .Values.app.componentName }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
stringData:
  replication-username: replication
  replication-password: {{ $random_patroni_replication_password | quote }}
  superuser-username: postgres
  superuser-password: {{ $random_patroni_superuser_password | quote }}
  app-db-name: {{ .Values.patroni.databaseName }}
  app-db-username: user{{ $random_patroni_app_user }}
  app-db-password: {{ $random_patroni_app_password | quote }}
  connect-string: Host={{ .Release.Name }}-{{ .Values.pgbouncer.componentName }};Port={{ .Values.pgbouncer.service.port }};Database={{ .Values.patroni.databaseName }};Username=user{{ $random_patroni_app_user }};Password={{ $random_patroni_app_password }}
{{- end -}}